root = "."
tmp_dir = ".air"

[build]
bin = "./.air/media-fetch --mode dev"
cmd = "go build -o ./.air/media-fetch ./main.go"
delay = 1000
exclude_dir = [".air", "web", "build","script"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
send_interrupt = true
kill_delay = 2000
